#! /bin/bash

if [ $# -gt 0 ]; then
	echo ERROR: No arguments should be provided while using this script
	exit 0
fi

echo Script downloads files from each URL provided in separate lines in file lista.txt

filename=lista.txt

while read -r line; do
	echo $line
	wget -q $line
done < "$filename"
