#! /bin/bash

if [ $# -ne 1 ]; then
	echo ERROR: Invalid number of arguments
	exit 0
fi

counter=0

echo Script counts and lists all executable files in $1

if [ -d $1 ]; then
	for file in ${1}/*; do
		if [ -x $file ]; then
			echo "$file"
			counter=`expr $counter + 1`
		fi
	done
	echo  Found $counter executable files
else
	echo ERROR: Given argument is not a directory
	exit 0
fi
