#! /bin/bash

if [ $# -ne 1 ]; then
	echo ERROR: Incorrect number of arguments
	exit 0
fi

echo Script removes every empty file in given directory, which is: $1

if [ -d $1 ]; then
	for file in ${1}/*; do
		if ! [ -s $file ]; then
			echo Removed $file
			rm $file
		fi
	done
else
	echo ERROR: Given argument is not a directory
	exit 0
fi
