#! /bin/bash

if [ $# -ne 1 ]; then
	echo ERROR: Incorrect number of arguments
	exit 0
fi

counter=0

if [ -d $1 ]; then
	for file in ${1}/*; do
		if ! [ -x $file ]; then
			counter=`expr $counter + 1`
			mv $file $file.$counter
		fi
	done
else
	echo ERROR: Given argument is not a directory
	exit 0
fi
